<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuickReport - Template Engine</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', sans-serif; background: #f0f2f5; color: #333; }
        .header { background: #2c3e50; color: white; padding: 1rem 2rem; }
        .header h1 { font-size: 1.4rem; }
        .header small { color: #95a5a6; }
        .container { max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
        .card { background: white; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .card h2 { margin-bottom: 1rem; font-size: 1.1rem; color: #2c3e50; }
        textarea { width: 100%; height: 120px; padding: 0.75rem; border: 1px solid #ddd; border-radius: 4px; font-family: monospace; font-size: 0.9rem; resize: vertical; }
        .btn { padding: 0.6rem 1.5rem; border: none; border-radius: 4px; cursor: pointer; font-size: 0.9rem; margin-right: 0.5rem; margin-top: 0.5rem; }
        .btn-primary { background: #3498db; color: white; }
        .btn-secondary { background: #95a5a6; color: white; }
        .btn:hover { opacity: 0.9; }
        .example { background: #f8f9fa; padding: 0.75rem; border-radius: 4px; font-family: monospace; font-size: 0.85rem; margin: 0.5rem 0; word-break: break-all; }
        .info { background: #eaf4fd; border-left: 3px solid #3498db; padding: 0.75rem; margin-bottom: 1rem; font-size: 0.9rem; }
        #output { min-height: 60px; }
        label { display: block; margin-bottom: 0.4rem; font-weight: 600; font-size: 0.9rem; }
        .encoded-preview { margin-top: 0.5rem; color: #666; font-size: 0.85rem; }
    </style>
</head>
<body>
    <div class="header">
        <h1>QuickReport</h1>
        <small>Dynamic Template Engine v1.2</small>
    </div>

    <div class="container">
        <div class="card">
            <h2>How It Works</h2>
            <div class="info">
                Templates are <strong>base64-encoded</strong> before submission to safely transport
                special characters, HTML, and embedded PHP expressions over HTTP.
                The server decodes and renders them with dynamic variable substitution.
            </div>
            <p style="font-size:0.9rem;">Supported template syntax: use <code>&lt;?= $variable ?&gt;</code> for dynamic values like dates, usernames, and calculations.</p>
        </div>

        <div class="card">
            <h2>Submit a Template</h2>

            <div style="margin-bottom: 1rem;">
                <label>Template (plain text):</label>
                <textarea id="rawTemplate" placeholder="Write your template here...">
<h2>Monthly Report</h2>
<p>Generated on: <?= date('Y-m-d H:i:s') ?></p>
<p>Author: <?= $author ?></p>
<p>Department: <?= $department ?></p>
<hr>
<p>This report was automatically generated by QuickReport.</p></textarea>
                <div class="encoded-preview">
                    Base64 preview: <span id="b64preview" style="font-family:monospace;"></span>
                </div>
            </div>

            <div style="margin-bottom: 1rem;">
                <label>Or paste base64-encoded template directly:</label>
                <textarea id="b64Template" placeholder="Paste base64 string here..."></textarea>
            </div>

            <div style="margin-bottom: 1rem;">
                <label>Author Name:</label>
                <input type="text" id="author" value="John Doe" style="padding:0.5rem; border:1px solid #ddd; border-radius:4px; width:100%;">
            </div>

            <div style="margin-bottom: 1rem;">
                <label>Department:</label>
                <input type="text" id="department" value="Engineering" style="padding:0.5rem; border:1px solid #ddd; border-radius:4px; width:100%;">
            </div>

            <button class="btn btn-primary" onclick="submitTemplate()">Render Template</button>
            <button class="btn btn-secondary" onclick="encodeTemplate()">Encode to Base64</button>
            <button class="btn btn-secondary" onclick="loadExample('report')">Example: Report</button>
            <button class="btn btn-secondary" onclick="loadExample('invoice')">Example: Invoice</button>
        </div>

        <div class="card">
            <h2>Rendered Output</h2>
            <div id="output" style="padding: 1rem; background: #fafafa; border-radius: 4px; border: 1px solid #eee;"></div>
        </div>

        <div class="card">
            <h2>API Usage</h2>
            <p style="font-size:0.9rem; margin-bottom:0.5rem;">You can also POST templates directly:</p>
            <div class="example">
                curl -X POST http://localhost:8080/render.php \<br>
                &nbsp;&nbsp;-d "template=PGgyPlRlc3Q8L2gyPg==" \<br>
                &nbsp;&nbsp;-d "author=Jane" \<br>
                &nbsp;&nbsp;-d "department=Sales"
            </div>
        </div>
    </div>

    <script>
        function encodeTemplate() {
            const raw = document.getElementById('rawTemplate').value;
            const encoded = btoa(raw);
            document.getElementById('b64Template').value = encoded;
            document.getElementById('b64preview').textContent = encoded.substring(0, 60) + '...';
        }

        function loadExample(type) {
            const examples = {
                report: `<h2>Monthly Report</h2>\n<p>Generated on: <?= date('Y-m-d H:i:s') ?></p>\n<p>Author: <?= $author ?></p>\n<p>Department: <?= $department ?></p>\n<hr>\n<p>This report was automatically generated by QuickReport.</p>`,
                invoice: `<h2>Invoice #<?= rand(1000, 9999) ?></h2>\n<p>Date: <?= date('F j, Y') ?></p>\n<p>Prepared by: <?= $author ?></p>\n<p>Department: <?= $department ?></p>\n<table border="1" cellpadding="8" style="border-collapse:collapse; margin-top:10px;">\n<tr><th>Item</th><th>Amount</th></tr>\n<tr><td>Consulting</td><td>$5,000</td></tr>\n<tr><td>Development</td><td>$12,000</td></tr>\n<tr><td><strong>Total</strong></td><td><strong>$17,000</strong></td></tr>\n</table>`
            };
            document.getElementById('rawTemplate').value = examples[type];
            encodeTemplate();
        }

        async function submitTemplate() {
            let b64 = document.getElementById('b64Template').value.trim();

            if (!b64) {
                const raw = document.getElementById('rawTemplate').value;
                b64 = btoa(raw);
            }

            const author = document.getElementById('author').value;
            const department = document.getElementById('department').value;

            const response = await fetch('render.php', {
                method: 'POST',
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: `template=${encodeURIComponent(b64)}&author=${encodeURIComponent(author)}&department=${encodeURIComponent(department)}`
            });

            const html = await response.text();
            document.getElementById('output').innerHTML = html;
        }

        // auto-encode on load
        encodeTemplate();
    </script>
</body>
</html>
